/*
 * AgentComponent.java
 *
 * Created on 08.11.2008, 18:19:03
 */

package de.podolak.agenten.agent;

import de.podolak.agenten.agent.Agent;

/**
 *
 * @version $version$
 * @author $author$
 */
public class AgentComponent extends javax.swing.JPanel {

    private Agent agent;

    public AgentComponent() {
        this(null);
    }

    public AgentComponent(Agent agent) {
        initComponents();
        setAgent(agent);
    }

    /**
     * @return the agent
     */
    public Agent getAgent() {
        return agent;
    }

    /**
     * @param agent the agent to set
     */
    public void setAgent(Agent agent) {
        this.agent = agent;

        if (agent != null) {
            setSize(agent.getSize(), agent.getSize());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
